apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: abbaskazi0612/elearning-backend:latest
          imagePullPolicy: Always   # ✅ MUST BE HERE
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URI
              value: "mongodb+srv://abbas:adnanabbas@nodeapplication.wywl28e.mongodb.net/?retryWrites=true&w=majority"
